#!/usr/bin/env python
"""
Example code for testing various techniques to assess impact on CIFAR10 accuracy.

__author__ = "Hide Inada"
__copyright__ = "Copyright 2018, Hide Inada"
__license__ = "The MIT License"
__email__ = "hideyuki@gmail.com"
"""

import os
import logging

import numpy as np
import sys

import keras

from keras.models import Model
from keras.layers import Input
from keras.layers import Conv2D
from keras.layers import MaxPool2D
from keras.layers import Flatten
from keras.layers import Dense
from keras.layers import BatchNormalization
from keras.layers import GlobalAveragePooling2D
from keras.layers import ReLU
from keras.optimizers import Adam

log = logging.getLogger(__name__)
logging.basicConfig(level=os.environ.get("LOGLEVEL", "INFO"))  # Change the 2nd arg to INFO to suppress debug logging

EPOCHS = 200


def train_and_predict():
    """Train the model and predict.

    This file downloads dataset via Keras util.
    """

    (x, y), (x_test, y_test) = keras.datasets.cifar10.load_data()

    # Change the value from 0<= x <= 255 in UINT8 to 0 <= x <= 1 in float
    x = x / 255.0
    x_test = x_test / 255.0

    y_oh = keras.utils.to_categorical(y, 10) * 1.0
    y_test_oh = keras.utils.to_categorical(y_test, 10)

    input_layer = Input(shape=(32, 32, 3))

    # 1
    layer = Conv2D(filters=64, kernel_size=3, strides=1)(input_layer)
    layer = BatchNormalization()(layer)
    layer = ReLU()(layer)

    # 2
    layer = Conv2D(filters=64, kernel_size=3, strides=1)(layer)
    layer = BatchNormalization()(layer)
    layer = ReLU()(layer)

    # 3
    layer = Conv2D(filters=64, kernel_size=3, strides=1)(layer)
    layer = BatchNormalization()(layer)
    layer = ReLU()(layer)

    # 4
    layer = Conv2D(filters=128, kernel_size=3, strides=1)(layer)
    layer = BatchNormalization()(layer)
    layer = ReLU()(layer)

    # 5
    layer = Conv2D(filters=128, kernel_size=3, strides=1)(layer)
    layer = BatchNormalization()(layer)
    layer = ReLU()(layer)

    # 6
    layer = Conv2D(filters=128, kernel_size=3, strides=2)(layer)
    layer = BatchNormalization()(layer)
    layer = ReLU()(layer)

    # 7
    layer = Conv2D(filters=256, kernel_size=3, strides=1)(layer)
    layer = BatchNormalization()(layer)
    layer = ReLU()(layer)

    # 8
    layer = Conv2D(filters=256, kernel_size=3, strides=1)(layer)
    layer = BatchNormalization()(layer)
    layer = ReLU()(layer)

    # 9
    layer = Conv2D(filters=256, kernel_size=3, strides=2)(layer)
    layer = BatchNormalization()(layer)
    layer = ReLU()(layer)

    layer = GlobalAveragePooling2D()(layer)

    last_layer = Dense(10, activation='softmax')(layer)

    model = Model(input_layer, last_layer)
    adam = Adam(lr=0.001, beta_1=0.9, beta_2=0.999)
    model.compile(adam, loss=keras.losses.categorical_crossentropy, metrics=[keras.metrics.categorical_accuracy])

    model.fit(x, y_oh, epochs=EPOCHS)

    # predict
    y_hat_oh = model.predict(x_test)
    total_size = y_hat_oh.shape[0]
    y_hat_int = np.argmax(y_hat_oh, axis=1)  # to int from one-hot vector
    y_hat_int = y_hat_int.reshape((y_hat_int.shape[0], 1))
    matched_indices = (y_hat_int == y_test)
    matched_count = y_test[matched_indices].shape[0]
    print("Matched: %d out of Total: %d (%f percent)" % (matched_count, total_size, matched_count * 100 / total_size))


def main():
    """Defines an application's main functionality"""
    train_and_predict()


if __name__ == "__main__":
    main()
